apiVersion: v1
kind: Pod
metadata:
  name: "kaniko"
  namespace: default
  labels:
    app: "kaniko"
spec:
  containers:
    - name: kaniko
      image: "gcr.io/kaniko-project/executor:debug"
      imagePullPolicy: Always
      args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/vprasadreddy/python-flask-webapp.git"
        - "--destination=aksdevclusteracr.azurecr.io/python-image-using-kaniko:2"
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-token
              key: GIT_TOKEN
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: azure-acr-secret
        items:
          - key: .dockerconfigjson
            path: config.json
