apiVersion: v1
kind: Pod
metadata:
  name: "kaniko"
  namespace: default
  labels:
    app: "kaniko"
spec:
  containers:
    - name: kaniko
      image: "gcr.io/kaniko-project/executor:debug"
      imagePullPolicy: Always
      args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/vprasadreddy/python-flask-webapp.git"
        - "--destination=prasadreddy2349/python-image-using-kaniko:latest"
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-registry-secret
        items:
          - key: .dockerconfigjson
            path: config.json
