name: kaniko-pipeline

on:
  # push:
  #   branches: [ "*" ]
  workflow_dispatch:

env:
  ACR_URL: "aksdevclusteracr.azurecr.io"
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

jobs:
  kaniko-build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
    permissions:
      contents: read

    # outputs:
    #   commit_sha_short: ${{ steps.commit_sha.outputs.sha_short }}
    steps:
      # - uses: actions/checkout@v2

      # - name: short commit sha
      #   id: commit_sha
      #   run: echo "sha_short=$(git log -1 --pretty=%h)" >> $GITHUB_OUTPUT

      # - name: print commit sha
      #   run: echo ${{ steps.commit_sha.outputs.sha_short }}

      - name: Build and Push Image with kaniko
        run: |
          /kaniko/executor --dockerfile="Dockerfile" --context="git://github.com/vprasadreddy/python-flask-webapp.git" --destination="aksdevclusteracr.azurecr.io/python-image-using-kaniko:3" --push-retry 3
        # env:
        #   AZURE_CLIENT_ID: ${{ secrets.ACR_SPN_CLIENT_ID }}
        #   AZURE_CLIENT_SECRET: ${{ secrets.ACR_SPN_PASSWORD }}
        #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
